  - type: web
    name: mi-frontend
    env: node
    buildCommand: npm install 
    startCommand: npm run start
    envVars:
      - key: REACT_APP_API_URL
        value: https://tf-backend-production.up.railway.app
      - key: PORT
        value: "8080"
      - key: PUBLIC_URL
        value: https://tf-frontend-production.up.railway.app/
